/**
 * @ecu/protocol-constants
 * Centralized timing constants and NRC codes (DRY principle)
 */

// ─── Default timeout values (milliseconds) ────────────────────────────────────

export const DEFAULT_SESSION_TIMEOUT_MS = 30000; // 30 seconds
export const DEFAULT_P2_TIMEOUT_MS = 50; // 50 milliseconds
export const DEFAULT_P3_TIMEOUT_MS = 5000; // 5 seconds
export const DEFAULT_SECURITY_TIMEOUT_MS = 30000; // 30 seconds

// ─── KWP2000 / UDS Negative Response Codes (NRC) ─────────────────────────────

export const NRC = {
  GENERAL_REJECT: 0x10,
  SERVICE_NOT_SUPPORTED: 0x11,
  SUB_FUNCTION_NOT_SUPPORTED: 0x12,
  INCORRECT_MESSAGE_LENGTH_OR_INVALID_FORMAT: 0x13,
  RESPONSE_TOO_LONG: 0x14,
  BUSY_REPEAT_REQUEST: 0x21,
  CONDITIONS_NOT_CORRECT: 0x22,
  REQUEST_SEQUENCE_ERROR: 0x24,
  REQUEST_OUT_OF_RANGE: 0x31,
  SECURITY_ACCESS_DENIED: 0x33,
  INVALID_KEY: 0x35,
  EXCEEDED_NUMBER_OF_ATTEMPTS: 0x36,
  REQUIRED_TIME_DELAY_NOT_EXPIRED: 0x37,
  UPLOAD_DOWNLOAD_NOT_ACCEPTED: 0x70,
  TRANSFER_DATA_SUSPENDED: 0x71,
  GENERAL_PROGRAMMING_FAILURE: 0x72,
  WRONG_BLOCK_SEQUENCE_COUNTER: 0x73,
  REQUEST_CORRECTLY_RECEIVED_RESPONSE_PENDING: 0x78,
  SUB_FUNCTION_NOT_SUPPORTED_IN_ACTIVE_SESSION: 0x7e,
  SERVICE_NOT_SUPPORTED_IN_ACTIVE_SESSION: 0x7f,
} as const;
